### ISSUE TITLE
use fields for AES_CTRL.KEY_LEN

### ISSUE THREAD

**Issue by xobs** [betrusted-io/gateware#2]
The current implementation uses hardcoded values that generate sphinx warnings and render like this:

![image](https://user-images.githubusercontent.com/238325/76313872-c1c8a480-6310-11ea-8445-b33f7ded4892.png)

By using values, this gets rendered as a table:

![image](https://user-images.githubusercontent.com/238325/76313943-e3c22700-6310-11ea-92ea-5b55419df821.png)

Additionally, these values will eventually be able to be exported in the svd file, though that functionality does not yet exist.

This patch can be used to convert to using values:

```patch
diff --git a/betrusted-soc.py b/betrusted-soc.py
index 1223477..04e5c3a 100755
--- a/betrusted-soc.py
+++ b/betrusted-soc.py
@@ -751,7 +751,11 @@ class Aes(Module, AutoDoc, AutoCSR):

         self.ctrl = CSRStorage(fields=[
             CSRField("mode", size=1, description="set to `0' for AES_ENC, `1` for AES_DEC"),
-            CSRField("key_len", size=3, description="`AES128`=001, `AES192`=010, `AES256`=100"),
+            CSRField("key_len", size=3, description="length of the aes block", values=[
+                    ("001", "AES128"),
+                    ("010", "AES192"),
+                    ("100", "AES256"),
+            ]),
             CSRField("manual_start", size=1, description="If `0`, operation starts as soon as all data words are written"),
             CSRField("force_data_overwrite", size=1, description="If `0`, output is not updated until it is read"),             ])
```

**Comment by bunnie** [comment]
I think you have push rights, you can go ahead and just fix bugs like this...i'll see the commit message when it goes through.

**Comment by xobs** [comment]
Sounds good.

(Also, this issue should have gone into "soc".  Oops.)
